name: qota-community-skins-dev

services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      NODE_ENV: development
      PORT: ${PORT:-3004}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${PORT:-3004}:${PORT:-3004}
    volumes:
      - .:/qota-community-skins-dev
      - /qota-community-skins-dev/node_modules
      - /qota-community-skins-dev/.nuxt
